# Generated by Django 3.0.6 on 2020-05-28 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_document', models.CharField(max_length=30, verbose_name='C.N.P.J')),
                ('company_name', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('key_name', models.CharField(max_length=20, verbose_name='Chave')),
                ('identify_name', models.CharField(max_length=20, verbose_name='Identificador')),
                ('data_value', models.CharField(max_length=200, verbose_name='Valor')),
                ('system_version', models.CharField(max_length=20, verbose_name='Versão')),
                ('date_insert', models.DateField(default=datetime.date.today, verbose_name='Inserido em')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
